### ISSUE TITLE
The lyric importer will crash if switch mode in edit lyric mode.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1012]
Callstack:
```
osu.Framework.Allocation.DependencyNotRegisteredException: The type DrawableLyricInputCaret has a dependency on ILyricTextChangeHandler, but the dependency is not registered.
   at osu.Framework.Allocation.ResolvedAttribute.<>c__DisplayClass7_0.<getDependency>b__0(IReadOnlyDependencyContainer dc)
   at osu.Framework.Allocation.ResolvedAttribute.<>c__DisplayClass6_1.<CreateActivator>b__2(Object target, IReadOnlyDependencyContainer dc)
   at osu.Framework.Allocation.ResolvedAttribute.<>c__DisplayClass6_0.<CreateActivator>b__1(Object target, IReadOnlyDependencyContainer dc)
   at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance)
   at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
   at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
   at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
   at osu.Framework.Graphics.Containers.Container`1.AddInternal(Drawable drawable)
   at osu.Framework.Graphics.Containers.Container`1.Add(T drawable)
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Rows.EditLyricRow.SingleLyricEditor.<InitializeCaret>g__addCaret|26_0(Boolean isPreview, <>c__DisplayClass26_0& ) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/Lyrics/Rows/EditLyricRow.cs:line 501
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Rows.EditLyricRow.SingleLyricEditor.InitializeCaret(LyricEditorMode mode) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/Lyrics/Rows/EditLyricRow.cs:line 490
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Rows.EditLyricRow.SingleLyricEditor.<.ctor>b__19_1(ValueChangedEvent`1 e) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/Lyrics/Rows/EditLyricRow.cs:line 343
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
   at osu.Framework.Bindables.Bindable`1.set_Value(T value)
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.LyricEditor.set_Mode(LyricEditorMode value) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/Lyrics/LyricEditor.cs:line 394
   at osu.Game.Rulesets.Karaoke.Edit.ImportLyric.EditLyric.EditLyricStepScreen.SwitchLyricEditorMode(LyricEditorMode mode) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/ImportLyric/EditLyric/EditLyricStepScreen.cs:line 54
   at osu.Game.Rulesets.Karaoke.Edit.ImportLyric.EditLyric.EditLyricStepScreen.EditLyricNavigation.EditLyricTextFlowContainer.<>c__DisplayClass0_0.<.ctor>b__1() in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/ImportLyric/EditLyric/EditLyricStepScreen.cs:line 111
   at osu.Game.Rulesets.Karaoke.Edit.ImportLyric.LyricImporterStepScreenWithTopNavigation.TopNavigation.NavigationTextContainer.ClickableSpriteText.OnClick(ClickEvent e) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/ImportLyric/LyricImporterStepScreenWithTopNavigation.cs:line 199
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at osu.Framework.Input.ButtonEventManager`1.<>c__DisplayClass14_0.<PropagateButtonEvent>b__0(Drawable target)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.MouseButtonEventManager.handleClick(InputState state, List`1 targets)
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
   at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.StateChanges.MouseButtonInput.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.PassThroughInputManager.Handle(UIEvent e)
   at osu.Framework.Graphics.Drawable.OnMouseUp(MouseUpEvent e)
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at osu.Framework.Input.ButtonEventManager`1.<>c__DisplayClass14_0.<PropagateButtonEvent>b__0(Drawable target)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
   at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.StateChanges.MouseButtonInput.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.InputManager.Update()
   at osu.Framework.Input.PassThroughInputManager.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.processFrame()
```

**Comment by andy840119** [comment]
Implemented.
