### ISSUE TITLE
Invest why cannot switch to karaoke ruleset in the lazer release.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1098]
log:
```
2022-02-05 13:03:24 [verbose]: ----------------------------------------------------------
2022-02-05 13:03:24 [verbose]: runtime Log for andy840119 (LogLevel: Verbose)
2022-02-05 13:03:24 [verbose]: Running osu 2022.127.0.0 on .NET 5.0.12
2022-02-05 13:03:24 [verbose]: Environment: macOS (Unix 11.0.0), 8 cores
2022-02-05 13:03:24 [verbose]: ----------------------------------------------------------
2022-02-05 13:03:24 [verbose]: GL Initialized
2022-02-05 13:03:24 [verbose]: GL Version:                 2.1 ATI-4.2.15
2022-02-05 13:03:24 [verbose]: GL Renderer:                AMD Radeon Pro 560 OpenGL Engine
2022-02-05 13:03:24 [verbose]: GL Shader Language version: 1.20
2022-02-05 13:03:24 [verbose]: GL Vendor:                  ATI Technologies Inc.
2022-02-05 13:03:24 [verbose]: GL Extensions:              GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_instanced_arrays GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_seamless_cube_map GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_shadow_ambient GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_blend_equation_separate GL_ATI_blend_weighted_minmax GL_ATI_separate_stencil GL_ATI_texture_compression_3dc GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_barrier GL_SGI_color_matrix GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod
2022-02-05 13:03:24 [verbose]: Host execution state changed to Running
2022-02-05 13:03:24 [verbose]: Execution mode changed to MultiThreaded
2022-02-05 13:03:25 [verbose]: Beginning realm file store cleanup
2022-02-05 13:03:25 [verbose]: Finished realm file store cleanup (0 of 121 deleted)
2022-02-05 13:03:25 [verbose]: 🔈 BASS initialised
2022-02-05 13:03:25 [verbose]: BASS version:           2.4.16.7
2022-02-05 13:03:25 [verbose]: BASS FX version:        2.4.12.6
2022-02-05 13:03:25 [verbose]: BASS MIX version:       2.4.11.1
2022-02-05 13:03:25 [verbose]: Device:                 Default
2022-02-05 13:03:25 [verbose]: Driver:
2022-02-05 13:03:25 [verbose]: Update period:          5 ms
2022-02-05 13:03:25 [verbose]: Device buffer length:   -1 ms
2022-02-05 13:03:25 [verbose]: Playback buffer length: 100 ms
2022-02-05 13:03:25 [error]: Failed to add ruleset osu.Game.Rulesets.Karaoke.Packed, Version=2022.205.0.0, Culture=neutral, PublicKeyToken=null
2022-02-05 13:03:25 [error]: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
2022-02-05 13:03:25 [error]: Method 'get_SizeMultiplier' in type 'osu.Game.Rulesets.Karaoke.Mods.KaraokeModFlashlight' from assembly 'osu.Game.Rulesets.Karaoke.Packed, Version=2022.205.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-02-05 13:03:25 [error]: at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2022-02-05 13:03:25 [error]: at System.Reflection.RuntimeModule.GetTypes()
2022-02-05 13:03:25 [error]: at System.Reflection.Assembly.GetTypes()
2022-02-05 13:03:25 [error]: at osu.Game.Rulesets.RulesetStore.addRuleset(Assembly assembly) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Rulesets/RulesetStore.cs:line 238
2022-02-05 13:03:25 [error]: System.TypeLoadException: Method 'get_SizeMultiplier' in type 'osu.Game.Rulesets.Karaoke.Mods.KaraokeModFlashlight' from assembly 'osu.Game.Rulesets.Karaoke.Packed, Version=2022.205.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-02-05 13:03:26 [verbose]: Game-wide working beatmap updated to please load a beatmap! - no beatmaps available!
2022-02-05 13:03:26 [verbose]: 📺 BackgroundScreenStack#277(depth:1) loading ScalingContainer+ScalingBackgroundScreen#885
2022-02-05 13:03:26 [verbose]: Loading VersionManager...
2022-02-05 13:03:26 [verbose]: Opened realm "/Users/andy840119/.local/share/osu/client.realm" at version 13
2022-02-05 13:03:27 [verbose]: 📺 BackgroundScreenStack#277(depth:1) entered ScalingContainer+ScalingBackgroundScreen#885
2022-02-05 13:03:27 [verbose]: Loaded VersionManager!
2022-02-05 13:03:27 [verbose]: Loading OsuLogo...
2022-02-05 13:03:27 [verbose]: Loaded OsuLogo!
2022-02-05 13:03:27 [verbose]: Loading Toolbar...
2022-02-05 13:03:27 [verbose]: 📺 OsuScreenStack#207(depth:1) loading Loader#393
2022-02-05 13:03:27 [verbose]: 📺 OsuScreenStack#207(depth:1) entered Loader#393
2022-02-05 13:03:27 [verbose]: 📺 OsuScreenStack#207(depth:1) suspended Loader#393 (waiting on Disclaimer#654)
2022-02-05 13:03:27 [verbose]: 📺 OsuScreenStack#207(depth:2) entered Disclaimer#654
2022-02-05 13:03:27 [verbose]: Loaded Toolbar!
2022-02-05 13:03:27 [verbose]: Loading VolumeOverlay...
2022-02-05 13:03:27 [verbose]: Loaded VolumeOverlay!
2022-02-05 13:03:27 [verbose]: Loading OnScreenDisplay...
2022-02-05 13:03:27 [verbose]: Loaded OnScreenDisplay!
2022-02-05 13:03:27 [verbose]: Loading NotificationOverlay...
2022-02-05 13:03:27 [verbose]: Loaded NotificationOverlay!
2022-02-05 13:03:27 [verbose]: Loading CollectionManager...
2022-02-05 13:03:27 [verbose]: Loaded CollectionManager!
2022-02-05 13:03:27 [verbose]: Loading LegacyImportManager...
2022-02-05 13:03:27 [verbose]: Loaded LegacyImportManager!
2022-02-05 13:03:27 [verbose]: Loading ScreenshotManager...
2022-02-05 13:03:27 [verbose]: Loaded ScreenshotManager!
2022-02-05 13:03:27 [verbose]: Loading SimpleUpdateManager...
2022-02-05 13:03:27 [verbose]: Loaded SimpleUpdateManager!
2022-02-05 13:03:27 [verbose]: Loading ManageCollectionsDialog...
2022-02-05 13:03:27 [verbose]: Loaded ManageCollectionsDialog!
2022-02-05 13:03:27 [verbose]: Loading BeatmapListingOverlay...
2022-02-05 13:03:28 [verbose]: Loaded BeatmapListingOverlay!
2022-02-05 13:03:28 [verbose]: Loading DashboardOverlay...
2022-02-05 13:03:28 [verbose]: Loaded DashboardOverlay!
2022-02-05 13:03:28 [verbose]: Loading NewsOverlay...
2022-02-05 13:03:29 [verbose]: Loaded NewsOverlay!
2022-02-05 13:03:29 [verbose]: Loading RankingsOverlay...
2022-02-05 13:03:29 [verbose]: Loaded RankingsOverlay!
2022-02-05 13:03:29 [verbose]: Loading ChannelManager...
2022-02-05 13:03:29 [verbose]: Chat is now polling every 60000 ms
2022-02-05 13:03:29 [verbose]: Loaded ChannelManager!
2022-02-05 13:03:29 [verbose]: Loading ChatOverlay...
2022-02-05 13:03:29 [verbose]: Loaded ChatOverlay!
2022-02-05 13:03:29 [verbose]: Loading MessageNotifier...
2022-02-05 13:03:29 [verbose]: Loaded MessageNotifier!
2022-02-05 13:03:29 [verbose]: Loading SettingsOverlay...
2022-02-05 13:03:29 [verbose]: Loaded SettingsOverlay!
2022-02-05 13:03:29 [verbose]: Loading ChangelogOverlay...
2022-02-05 13:03:29 [verbose]: Loaded ChangelogOverlay!
2022-02-05 13:03:29 [verbose]: Loading UserProfileOverlay...
2022-02-05 13:03:29 [verbose]: Loaded UserProfileOverlay!
2022-02-05 13:03:29 [verbose]: Loading BeatmapSetOverlay...
2022-02-05 13:03:29 [verbose]: Loaded BeatmapSetOverlay!
2022-02-05 13:03:29 [verbose]: Loading WikiOverlay...
2022-02-05 13:03:29 [verbose]: Loaded WikiOverlay!
2022-02-05 13:03:29 [verbose]: Loading SkinEditorOverlay...
2022-02-05 13:03:29 [verbose]: Loaded SkinEditorOverlay!
2022-02-05 13:03:29 [verbose]: Loading LoginOverlay...
2022-02-05 13:03:29 [verbose]: Loaded LoginOverlay!
2022-02-05 13:03:29 [verbose]: Loading NowPlayingOverlay...
2022-02-05 13:03:29 [verbose]: Loaded NowPlayingOverlay!
2022-02-05 13:03:29 [verbose]: Loading AccountCreationOverlay...
2022-02-05 13:03:29 [verbose]: 📺 ScreenStack#319(depth:1) scheduling push ScreenWelcome#381
2022-02-05 13:03:29 [verbose]: Loaded AccountCreationOverlay!
2022-02-05 13:03:29 [verbose]: Loading DialogOverlay...
2022-02-05 13:03:29 [verbose]: Loaded DialogOverlay!
2022-02-05 13:03:29 [verbose]: Loading HighPerformanceSession...
2022-02-05 13:03:29 [verbose]: Loaded HighPerformanceSession!
2022-02-05 13:03:33 [verbose]: 📺 OsuScreenStack#207(depth:2) suspended Disclaimer#654 (waiting on IntroTriangles#207)
2022-02-05 13:03:33 [verbose]: 📺 OsuScreenStack#207(depth:3) entered IntroTriangles#207
2022-02-05 13:03:33 [verbose]: 📺 BackgroundScreenStack#499(depth:1) loading BackgroundScreenDefault#478
2022-02-05 13:03:33 [verbose]: Game-wide working beatmap updated to cYsmix - triangles (peppy) [peppy]
2022-02-05 13:03:33 [verbose]: 📺 BackgroundScreenStack#499(depth:1) entered BackgroundScreenDefault#478
2022-02-05 13:03:33 [verbose]: decoupled ruleset transferred ("" -> "osu!mania")
2022-02-05 13:03:36 [verbose]: 📺 OsuScreenStack#207(depth:3) suspended IntroTriangles#207 (waiting on MainMenu#574)
2022-02-05 13:03:36 [verbose]: 📺 OsuScreenStack#207(depth:4) entered MainMenu#574
2022-02-05 13:03:37 [verbose]: ButtonSystem's state changed from Initial to TopLevel
2022-02-05 13:03:37 [verbose]: ⚠️ Failed to add ruleset osu.Game.Rulesets.Karaoke.Packed, Version=2022.205.0.0, Culture=neutral, PublicKeyToken=null
2022-02-05 13:03:37 [verbose]: 
2022-02-05 13:03:37 [verbose]: This error has been automatically reported to the devs.
2022-02-05 13:03:37 [verbose]: ⚠️ A newer release of osu! has been found (2022.127.0 → 2022.205.0).
2022-02-05 13:03:37 [verbose]: 
2022-02-05 13:03:37 [verbose]: Click here to download the new version, which can be installed over the top of your existing installation
2022-02-05 13:03:38 [error]: An unhandled error has occurred.
2022-02-05 13:03:38 [error]: System.TypeLoadException: Method 'get_SizeMultiplier' in type 'osu.Game.Rulesets.Karaoke.Mods.KaraokeModFlashlight' from assembly 'osu.Game.Rulesets.Karaoke.Packed, Version=2022.205.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-02-05 13:03:38 [error]: at osu.Game.Rulesets.Karaoke.KaraokeRuleset.GetModsFor(ModType type)
2022-02-05 13:03:38 [error]: at osu.Game.OsuGameBase.onRulesetChanged(ValueChangedEvent`1 r) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/OsuGameBase.cs:line 474
2022-02-05 13:03:38 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2022-02-05 13:03:38 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2022-02-05 13:03:38 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2022-02-05 13:03:38 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2022-02-05 13:03:38 [error]: at osu.Framework.Graphics.UserInterface.TabControl`1.SelectTab(TabItem`1 tab)
2022-02-05 13:03:38 [error]: at osu.Framework.Graphics.UserInterface.TabControl`1.activationRequested(TabItem`1 tab)
2022-02-05 13:03:38 [error]: at osu.Framework.Graphics.UserInterface.TabItem`1.OnClick(ClickEvent e)
2022-02-05 13:03:38 [error]: at osu.Framework.Graphics.Drawable.TriggerClick()
2022-02-05 13:03:38 [error]: at osu.Game.Overlays.Toolbar.ToolbarRulesetTabButton.RulesetButton.OnClick(ClickEvent e) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Overlays/Toolbar/ToolbarRulesetTabButton.cs:line 65
2022-02-05 13:03:38 [error]: at osu.Framework.Input.ButtonEventManager`1.<>c__DisplayClass14_0.<PropagateButtonEvent>b__0(Drawable target)
2022-02-05 13:03:38 [error]: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
2022-02-05 13:03:38 [error]: at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
2022-02-05 13:03:38 [error]: at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
2022-02-05 13:03:38 [error]: at osu.Framework.Input.MouseButtonEventManager.handleClick(InputState state, List`1 targets)
2022-02-05 13:03:38 [error]: at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
2022-02-05 13:03:38 [error]: at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
2022-02-05 13:03:38 [error]: at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
2022-02-05 13:03:38 [error]: at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
2022-02-05 13:03:38 [error]: at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
2022-02-05 13:03:38 [error]: at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
2022-02-05 13:03:38 [error]: at osu.Framework.Input.StateChanges.MouseButtonInput.Apply(InputState state, IInputStateChangeHandler handler)
2022-02-05 13:03:38 [error]: at osu.Framework.Input.InputManager.Update()
2022-02-05 13:03:38 [error]: at osu.Framework.Input.PassThroughInputManager.Update()
2022-02-05 13:03:38 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-02-05 13:03:38 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-05 13:03:38 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2022-02-05 13:03:38 [error]: at osu.Framework.Threading.GameThread.processFrame()
2022-02-05 13:03:38 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2022-02-05 13:03:38 [verbose]: ⚠️ An unhandled error has occurred.
2022-02-05 13:03:38 [verbose]: 
2022-02-05 13:03:38 [verbose]: This error has been automatically reported to the devs.

```

**Comment by andy840119** [comment]
Can be closed due to not being updated to the latest lazer.
