### ISSUE TITLE
Invest the reason why cannot enter the editor in release lezer.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1102]
There's the log:
```
2022-02-06 05:14:12 [verbose]: ----------------------------------------------------------
2022-02-06 05:14:12 [verbose]: runtime Log for andy840119 (LogLevel: Verbose)
2022-02-06 05:14:12 [verbose]: Running osu 2022.205.0.0 on .NET 5.0.12
2022-02-06 05:14:12 [verbose]: Environment: macOS (Unix 11.0.0), 8 cores
2022-02-06 05:14:12 [verbose]: ----------------------------------------------------------
2022-02-06 05:14:12 [verbose]: Detect: Searching for tablets...
2022-02-06 05:14:12 [verbose]: Detect: No tablets were detected.
2022-02-06 05:14:12 [verbose]: GL Initialized
2022-02-06 05:14:12 [verbose]: GL Version:                 2.1 ATI-4.2.15
2022-02-06 05:14:12 [verbose]: GL Renderer:                AMD Radeon Pro 560 OpenGL Engine
2022-02-06 05:14:12 [verbose]: GL Shader Language version: 1.20
2022-02-06 05:14:12 [verbose]: GL Vendor:                  ATI Technologies Inc.
2022-02-06 05:14:12 [verbose]: GL Extensions:              GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_instanced_arrays GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_seamless_cube_map GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_shadow_ambient GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_blend_equation_separate GL_ATI_blend_weighted_minmax GL_ATI_separate_stencil GL_ATI_texture_compression_3dc GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_barrier GL_SGI_color_matrix GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod
2022-02-06 05:14:12 [verbose]: Host execution state changed to Running
2022-02-06 05:14:12 [verbose]: Execution mode changed to MultiThreaded
2022-02-06 05:14:13 [verbose]: 🔈 BASS initialised
2022-02-06 05:14:13 [verbose]: BASS version:           2.4.16.7
2022-02-06 05:14:13 [verbose]: BASS FX version:        2.4.12.6
2022-02-06 05:14:13 [verbose]: BASS MIX version:       2.4.11.1
2022-02-06 05:14:13 [verbose]: Device:                 Default
2022-02-06 05:14:13 [verbose]: Driver:
2022-02-06 05:14:13 [verbose]: Update period:          5 ms
2022-02-06 05:14:13 [verbose]: Device buffer length:   -1 ms
2022-02-06 05:14:13 [verbose]: Playback buffer length: 100 ms
2022-02-06 05:14:13 [verbose]: Beginning realm file store cleanup
2022-02-06 05:14:13 [verbose]: Finished realm file store cleanup (0 of 298 deleted)
2022-02-06 05:14:13 [verbose]: Game-wide working beatmap updated to please load a beatmap! - no beatmaps available!
2022-02-06 05:14:14 [verbose]: Loading VersionManager...
2022-02-06 05:14:14 [verbose]: 📺 BackgroundScreenStack#396(depth:1) loading ScalingContainer+ScalingBackgroundScreen#667
2022-02-06 05:14:14 [verbose]: Opened realm "/Users/andy840119/.local/share/osu/client.realm" at version 13
2022-02-06 05:14:14 [verbose]: 📺 BackgroundScreenStack#396(depth:1) entered ScalingContainer+ScalingBackgroundScreen#667
2022-02-06 05:14:14 [verbose]: Loaded VersionManager!
2022-02-06 05:14:14 [verbose]: Loading OsuLogo...
2022-02-06 05:14:14 [verbose]: Loaded OsuLogo!
2022-02-06 05:14:14 [verbose]: Loading Toolbar...
2022-02-06 05:14:14 [verbose]: 📺 OsuScreenStack#637(depth:1) loading Loader#458
2022-02-06 05:14:14 [verbose]: 📺 OsuScreenStack#637(depth:1) entered Loader#458
2022-02-06 05:14:14 [verbose]: 📺 OsuScreenStack#637(depth:1) suspended Loader#458 (waiting on Disclaimer#330)
2022-02-06 05:14:14 [verbose]: 📺 OsuScreenStack#637(depth:2) entered Disclaimer#330
2022-02-06 05:14:14 [verbose]: Loaded Toolbar!
2022-02-06 05:14:14 [verbose]: Loading VolumeOverlay...
2022-02-06 05:14:14 [verbose]: Loaded VolumeOverlay!
2022-02-06 05:14:14 [verbose]: Loading OnScreenDisplay...
2022-02-06 05:14:14 [verbose]: Loaded OnScreenDisplay!
2022-02-06 05:14:14 [verbose]: Loading NotificationOverlay...
2022-02-06 05:14:15 [verbose]: Loaded NotificationOverlay!
2022-02-06 05:14:15 [verbose]: Loading CollectionManager...
2022-02-06 05:14:15 [verbose]: Loaded CollectionManager!
2022-02-06 05:14:15 [verbose]: Loading LegacyImportManager...
2022-02-06 05:14:15 [verbose]: Loaded LegacyImportManager!
2022-02-06 05:14:15 [verbose]: Loading ScreenshotManager...
2022-02-06 05:14:15 [verbose]: Loaded ScreenshotManager!
2022-02-06 05:14:15 [verbose]: Loading SimpleUpdateManager...
2022-02-06 05:14:15 [verbose]: Loaded SimpleUpdateManager!
2022-02-06 05:14:15 [verbose]: Loading ManageCollectionsDialog...
2022-02-06 05:14:15 [verbose]: Loaded ManageCollectionsDialog!
2022-02-06 05:14:15 [verbose]: Loading BeatmapListingOverlay...
2022-02-06 05:14:16 [verbose]: Loaded BeatmapListingOverlay!
2022-02-06 05:14:16 [verbose]: Loading DashboardOverlay...
2022-02-06 05:14:16 [verbose]: Loaded DashboardOverlay!
2022-02-06 05:14:16 [verbose]: Loading NewsOverlay...
2022-02-06 05:14:16 [verbose]: Loaded NewsOverlay!
2022-02-06 05:14:16 [verbose]: Loading RankingsOverlay...
2022-02-06 05:14:16 [verbose]: Loaded RankingsOverlay!
2022-02-06 05:14:16 [verbose]: Loading ChannelManager...
2022-02-06 05:14:16 [verbose]: Chat is now polling every 60000 ms
2022-02-06 05:14:16 [verbose]: Loaded ChannelManager!
2022-02-06 05:14:16 [verbose]: Loading ChatOverlay...
2022-02-06 05:14:16 [verbose]: Loaded ChatOverlay!
2022-02-06 05:14:16 [verbose]: Loading MessageNotifier...
2022-02-06 05:14:16 [verbose]: Loaded MessageNotifier!
2022-02-06 05:14:16 [verbose]: Loading SettingsOverlay...
2022-02-06 05:14:16 [verbose]: Loaded SettingsOverlay!
2022-02-06 05:14:16 [verbose]: Loading ChangelogOverlay...
2022-02-06 05:14:16 [verbose]: Loaded ChangelogOverlay!
2022-02-06 05:14:16 [verbose]: Loading UserProfileOverlay...
2022-02-06 05:14:16 [verbose]: Loaded UserProfileOverlay!
2022-02-06 05:14:16 [verbose]: Loading BeatmapSetOverlay...
2022-02-06 05:14:17 [verbose]: Loaded BeatmapSetOverlay!
2022-02-06 05:14:17 [verbose]: Loading WikiOverlay...
2022-02-06 05:14:17 [verbose]: Loaded WikiOverlay!
2022-02-06 05:14:17 [verbose]: Loading SkinEditorOverlay...
2022-02-06 05:14:17 [verbose]: Loaded SkinEditorOverlay!
2022-02-06 05:14:17 [verbose]: Loading LoginOverlay...
2022-02-06 05:14:17 [verbose]: Loaded LoginOverlay!
2022-02-06 05:14:17 [verbose]: Loading NowPlayingOverlay...
2022-02-06 05:14:17 [verbose]: Loaded NowPlayingOverlay!
2022-02-06 05:14:17 [verbose]: Loading AccountCreationOverlay...
2022-02-06 05:14:17 [verbose]: 📺 ScreenStack#122(depth:1) scheduling push ScreenWelcome#516
2022-02-06 05:14:17 [verbose]: Loaded AccountCreationOverlay!
2022-02-06 05:14:17 [verbose]: Loading DialogOverlay...
2022-02-06 05:14:17 [verbose]: Loaded DialogOverlay!
2022-02-06 05:14:17 [verbose]: Loading HighPerformanceSession...
2022-02-06 05:14:17 [verbose]: Loaded HighPerformanceSession!
2022-02-06 05:14:21 [verbose]: 📺 OsuScreenStack#637(depth:2) suspended Disclaimer#330 (waiting on IntroTriangles#636)
2022-02-06 05:14:21 [verbose]: 📺 OsuScreenStack#637(depth:3) entered IntroTriangles#636
2022-02-06 05:14:21 [verbose]: 📺 BackgroundScreenStack#335(depth:1) loading BackgroundScreenDefault#375
2022-02-06 05:14:21 [verbose]: Game-wide working beatmap updated to cYsmix - triangles (peppy) [peppy]
2022-02-06 05:14:21 [verbose]: 📺 BackgroundScreenStack#335(depth:1) entered BackgroundScreenDefault#375
2022-02-06 05:14:21 [verbose]: decoupled ruleset transferred ("" -> "karaoke!")
2022-02-06 05:14:24 [verbose]: 📺 OsuScreenStack#637(depth:3) suspended IntroTriangles#636 (waiting on MainMenu#501)
2022-02-06 05:14:24 [verbose]: 📺 OsuScreenStack#637(depth:4) entered MainMenu#501
2022-02-06 05:14:25 [verbose]: ButtonSystem's state changed from Initial to TopLevel
2022-02-06 05:14:26 [verbose]: ButtonSystem's state changed from TopLevel to Play
2022-02-06 05:14:26 [verbose]: 📺 OsuScreenStack#637(depth:4) suspended MainMenu#501 (waiting on PlaySongSelect#369)
2022-02-06 05:14:26 [verbose]: ButtonSystem's state changed from Play to EnteringMode
2022-02-06 05:14:26 [verbose]: 📺 OsuScreenStack#637(depth:5) entered PlaySongSelect#369
2022-02-06 05:14:26 [verbose]: 📺 BackgroundScreenStack#335(depth:2) loading BackgroundScreenBeatmap#319
2022-02-06 05:14:26 [verbose]: 📺 BackgroundScreenStack#335(depth:2) suspended BackgroundScreenDefault#375 (waiting on BackgroundScreenBeatmap#319)
2022-02-06 05:14:26 [verbose]: 📺 BackgroundScreenStack#335(depth:2) entered BackgroundScreenBeatmap#319
2022-02-06 05:14:26 [verbose]: updating selection with beatmap:640b7541-9f11-480a-a2d3-75fedf9f6b3e ruleset:karaoke!
2022-02-06 05:14:26 [verbose]: beatmap changed from "cYsmix - triangles (peppy) [peppy]" to "森田交一 - Shinning star (andy840119) [Normal]"
2022-02-06 05:14:26 [verbose]: Game-wide working beatmap updated to 森田交一 - Shinning star (andy840119) [Normal]
2022-02-06 05:14:26 [verbose]: Song select working beatmap updated to 森田交一 - Shinning star (andy840119) [Normal]
2022-02-06 05:14:28 [verbose]: 📺 OsuScreenStack#637(depth:5) suspended PlaySongSelect#369 (waiting on EditorLoader#558)
2022-02-06 05:14:28 [verbose]: 📺 OsuScreenStack#637(depth:6) loading EditorLoader#558
2022-02-06 05:14:28 [verbose]: 📺 OsuScreenStack#637(depth:6) entered EditorLoader#558
2022-02-06 05:14:28 [verbose]: 📺 OsuScreenStack#637(depth:6) suspended EditorLoader#558 (waiting on Editor#544)
2022-02-06 05:14:28 [verbose]: 📺 OsuScreenStack#637(depth:7) loading Editor#544
2022-02-06 05:14:28 [verbose]: 📺 OsuScreenStack#637(depth:7) entered Editor#544
2022-02-06 05:14:29 [error]: An unhandled error has occurred.
2022-02-06 05:14:29 [error]: osu.Framework.Allocation.DependencyNotRegisteredException: The type KaraokePlayfieldAdjustmentContainer has a dependency on KaraokeRulesetConfigManager, but the dependency is not registered.
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass7_0.<getDependency>b__0(IReadOnlyDependencyContainer dc)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-02-06 05:14:29 [error]: --- End of stack trace from previous location ---
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddRangeInternal(IEnumerable`1 range)
2022-02-06 05:14:29 [error]: at osu.Game.Rulesets.Edit.HitObjectComposer`1.load() in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Rulesets/Edit/HitObjectComposer.cs:line 102
2022-02-06 05:14:29 [error]: --- End of stack trace from previous location ---
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-02-06 05:14:29 [error]: --- End of stack trace from previous location ---
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-02-06 05:14:29 [error]: --- End of stack trace from previous location ---
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-02-06 05:14:29 [error]: --- End of stack trace from previous location ---
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Drawable.LoadFromAsync(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadComponents[TLoadable](List`1 components, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext, CancellationToken cancellation)
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass17_0`1.<LoadComponentsAsync>b__1()
2022-02-06 05:14:29 [error]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2022-02-06 05:14:29 [error]: --- End of stack trace from previous location ---
2022-02-06 05:14:29 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2022-02-06 05:14:29 [error]: --- End of stack trace from previous location ---
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass17_2`1.<LoadComponentsAsync>b__4()
2022-02-06 05:14:29 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2022-02-06 05:14:29 [error]: at osu.Framework.Threading.Scheduler.Update()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-02-06 05:14:29 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2022-02-06 05:14:29 [error]: at osu.Framework.Threading.GameThread.processFrame()
2022-02-06 05:14:29 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2022-02-06 05:14:29 [verbose]: ⚠️ An unhandled error has occurred.
2022-02-06 05:14:29 [verbose]: 
2022-02-06 05:14:29 [verbose]: This error has been automatically reported to the devs.
```
.
Technically it should be able to enter the editor because no error in `IEditorChangeHandler`.

**Comment by andy840119** [comment]
seems `KaraokeRulesetConfigManager` is missing in `KaraokePlayfieldAdjustmentContainer`...

**Comment by andy840119** [comment]
note that ruleset config manage should be cached in the `DrawableRulesetDependencies` in `DrawableRuleset` or (`DrawableKaraokeEditorRuleset`)

**Comment by andy840119** [comment]
Fixed.
