### ISSUE TITLE
Invest the case that cannot open singer editor

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1146]
![image](https://user-images.githubusercontent.com/9100368/156573206-5da5d265-c9ee-4e15-9f85-ded3a04e57a0.png)
here's the log:
```
2022-03-03 13:20:39 [error]: An unhandled error has occurred.
2022-03-03 13:20:39 [error]: osu.Framework.Graphics.Drawable+InvalidThreadForMutationException: Cannot mutate the InternalChildren on a Loaded Drawable while not on the update thread. Consider using Schedule to schedule the mutation operation.
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Drawable.EnsureMutationAllowed(String action)
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.ChangeInternalChildDepth(Drawable child, Single newDepth)
2022-03-03 13:20:39 [error]: at osu.Game.Screens.Edit.Compose.Components.EditorBlueprintContainer.OnBlueprintDeselected(SelectionBlueprint`1 blueprint) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Screens/Edit/Compose/Components/EditorBlueprintContainer.cs:line 149
2022-03-03 13:20:39 [error]: at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer`1.<load>b__23_0(Object selectedObjects, NotifyCollectionChangedEventArgs args) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs:line 58
2022-03-03 13:20:39 [error]: at osu.Framework.Bindables.BindableList`1.removeAll(Predicate`1 match, BindableList`1 caller)
2022-03-03 13:20:39 [error]: at osu.Framework.Bindables.BindableList`1.removeAll(Predicate`1 match, BindableList`1 caller)
2022-03-03 13:20:39 [error]: at osu.Game.Rulesets.Karaoke.Utils.BindablesUtils.<>c__DisplayClass1_0`2.<OnyWaySync>b__0(Object _, NotifyCollectionChangedEventArgs args)
2022-03-03 13:20:39 [error]: at osu.Framework.Bindables.BindableList`1.clear(BindableList`1 caller)
2022-03-03 13:20:39 [error]: at osu.Game.Rulesets.Karaoke.Edit.Singers.SingerScreen.PopOut()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.VisibilityContainer.LoadAsyncComplete()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Drawable.LoadFromAsync(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadComponents[TLoadable](List`1 components, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext, CancellationToken cancellation)
2022-03-03 13:20:39 [error]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2022-03-03 13:20:39 [error]: --- End of stack trace from previous location ---
2022-03-03 13:20:39 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2022-03-03 13:20:39 [error]: --- End of stack trace from previous location ---
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass17_2`1.<LoadComponentsAsync>b__4()
2022-03-03 13:20:39 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2022-03-03 13:20:39 [error]: at osu.Framework.Threading.Scheduler.Update()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-03 13:20:39 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2022-03-03 13:20:39 [error]: at osu.Framework.Threading.GameThread.processFrame()
2022-03-03 13:20:39 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2022-03-03 13:20:39 [verbose]: ⚠️ Subsequent messages have been logged. Click to view log files.

```

**Comment by andy840119** [comment]
![image](https://user-images.githubusercontent.com/9100368/156573375-90f9cab4-0615-4130-a7c6-4f3d5785ec64.png)
It works after second open.

**Comment by andy840119** [comment]
guess it's caused randomly.
might be the reason that init time is too long.

**Comment by andy840119** [comment]
Fixing.
