### ISSUE TITLE
Fix cause the crash after tab in the edit note text area.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1196]
![image](https://user-images.githubusercontent.com/9100368/158616200-316d3465-5392-47af-8e24-97aa60f5d0b3.png)
![image](https://user-images.githubusercontent.com/9100368/158615800-95c076f0-f50e-490a-b505-748ccd4f0827.png)
Caused because note text leave the focus, which cause text cannot be submitted.

Callstack:
```
System.InvalidOperationException: Should be exactly one THitObject being selected.
   at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.HitObjectChangeHandler`1.CheckExactlySelectedOneHitObject() in D:\Github\karaoke-dev\karaoke\osu.Game.Rulesets.Karaoke\Edit\ChangeHandlers\HitObjectChangeHandler.cs:line 24
   at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.Notes.NotesChangeHandler.ChangeText(String text) in D:\Github\karaoke-dev\karaoke\osu.Game.Rulesets.Karaoke\Edit\ChangeHandlers\Notes\NotesChangeHandler.cs:line 75
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Extends.Notes.NoteEditPropertySection.LabelledNoteTextTextBox.ApplyValue(Note note, String value) in D:\Github\karaoke-dev\karaoke\osu.Game.Rulesets.Karaoke\Edit\Lyrics\Extends\Notes\NoteEditPropertySection.cs:line 97
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Extends.Components.LabelledObjectFieldTextBox`1.<>c__DisplayClass5_0.<.ctor>b__1(TextBox sender, Boolean _) in D:\Github\karaoke-dev\karaoke\osu.Game.Rulesets.Karaoke\Edit\Lyrics\Extends\Components\LabelledObjectFieldTextBox.cs:line 53
   at osu.Game.Graphics.UserInterfaceV2.LabelledTextBox.<CreateComponent>b__18_1(TextBox sender, Boolean newText)
   at osu.Framework.Graphics.UserInterface.TextBox.Commit()
   at osu.Framework.Graphics.UserInterface.TextBox.OnFocusLost(FocusLostEvent e)
   at osu.Framework.Graphics.UserInterface.BasicTextBox.OnFocusLost(FocusLostEvent e)
   at osu.Game.Graphics.UserInterface.OsuTextBox.OnFocusLost(FocusLostEvent e)
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Extends.Components.LabelledObjectFieldTextBox`1.ObjectFieldTextBox.OnFocusLost(FocusLostEvent e) in D:\Github\karaoke-dev\karaoke\osu.Game.Rulesets.Karaoke\Edit\Lyrics\Extends\Components\LabelledObjectFieldTextBox.cs:line 135
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at osu.Framework.Input.InputManager.ChangeFocus(Drawable potentialFocusTarget, InputState state)
   at osu.Framework.Input.InputManager.ChangeFocus(Drawable potentialFocusTarget)
   at osu.Framework.Graphics.Containers.TabbableContainer`1.OnKeyDown(KeyDownEvent e)
   at osu.Framework.Graphics.UserInterface.TextBox.OnKeyDown(KeyDownEvent e)
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at osu.Framework.Input.ButtonEventManager`1.<>c__DisplayClass14_0.<PropagateButtonEvent>b__0(Drawable target)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.KeyEventManager.HandleButtonDown(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonDown(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleKeyboardKeyStateChange(ButtonStateChangeEvent`1 keyboardKeyStateChange)
   at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.InputManager.Update()
   at osu.Framework.Input.PassThroughInputManager.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.processFrame()
```

**Comment by andy840119** [comment]
Guess related to #1179
.
Also:
- note ruby text might have the same issue.
- ~~should check that is note display button applies to the notes(maybe not)?~~ -> tested and it works.

**Comment by andy840119** [comment]
Note:
- need to invest because caret does not change after focusing out the textbox.

**Comment by andy840119** [comment]
Fixed.
