### ISSUE TITLE
Fix cannot delete the lyric if contains time.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1202]
![image](https://user-images.githubusercontent.com/9100368/159022173-8b8f249b-bcf2-4599-a804-a39b5d4348d0.png)
It will cause the error in the perform on selecting.

Here's the call stack:
```
System.InvalidOperationException: Can not change depth of drawable which is not contained within this CompositeDrawable.
   at osu.Framework.Graphics.Containers.CompositeDrawable.ChangeInternalChildDepth(Drawable child, Single newDepth)
   at osu.Framework.Graphics.Containers.Container`1.ChangeChildDepth(T child, Single newDepth)
   at osu.Framework.Graphics.Containers.Container`1.ChangeChildDepth(T child, Single newDepth)
   at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer`1.OnBlueprintDeselected(SelectionBlueprint`1 blueprint)
   at osu.Game.Screens.Edit.Compose.Components.EditorBlueprintContainer.OnBlueprintDeselected(SelectionBlueprint`1 blueprint)
   at osu.Game.Rulesets.Edit.SelectionBlueprint`1.updateState()
   at osu.Game.Rulesets.Edit.SelectionBlueprint`1.set_State(SelectionState value)
   at osu.Game.Rulesets.Edit.SelectionBlueprint`1.Deselect()
   at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer`1.RemoveBlueprintFor(T item)
   at osu.Game.Screens.Edit.EditorBeatmap.UpdateState()
   at osu.Game.Screens.Edit.TransactionalCommitComponent.EndChange()
   at osu.Game.Screens.Edit.EditorBeatmap.PerformOnSelection(Action`1 action)
   at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.HitObjectChangeHandler`1.PerformOnSelection(Action`1 action) in D:\Github\karaoke-dev\karaoke\osu.Game.Rulesets.Karaoke\Edit\ChangeHandlers\HitObjectChangeHandler.cs:line 27
   at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.Lyrics.LyricsChangeHandler.Split(Int32 index) in D:\Github\karaoke-dev\karaoke\osu.Game.Rulesets.Karaoke\Edit\ChangeHandlers\Lyrics\LyricsChangeHandler.cs:line 18
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Rows.EditLyricRow.SingleLyricEditor.OnDoubleClick(DoubleClickEvent e) in D:\Github\karaoke-dev\karaoke\osu.Game.Rulesets.Karaoke\Edit\Lyrics\Rows\EditLyricRow.cs:line 424
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at osu.Framework.Input.ButtonEventManager`1.<>c__DisplayClass14_0.<PropagateButtonEvent>b__0(Drawable target)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.MouseButtonEventManager.handleDoubleClick(InputState state, List`1 targets)
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonDown(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonDown(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
   at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.StateChanges.MouseButtonInput.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.InputManager.Update()
   at osu.Framework.Input.PassThroughInputManager.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.processFrame()
```

**Comment by andy840119** [comment]
Note: 
it will have a similar bug if delete the lyric in the main editor.
seems will cause only if lyric has start end and time(?)

**Comment by andy840119** [comment]
Seems not caused in the lazer.

**Comment by andy840119** [comment]
Guess should resolved this shit first:
```
2022-03-18 15:12:56 [error]: An unhandled error has occurred.
2022-03-18 15:12:56 [error]: System.InvalidOperationException: Can not change depth of drawable which is not contained within this CompositeDrawable.
2022-03-18 15:12:56 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.ChangeInternalChildDepth(Drawable child, Single newDepth)
2022-03-18 15:12:56 [error]: at osu.Framework.Graphics.Containers.Container`1.ChangeChildDepth(T child, Single newDepth)
2022-03-18 15:12:56 [error]: at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer`1.OnBlueprintDeselected(SelectionBlueprint`1 blueprint)
2022-03-18 15:12:56 [error]: at osu.Game.Screens.Edit.Compose.Components.EditorBlueprintContainer.OnBlueprintDeselected(SelectionBlueprint`1 blueprint)
2022-03-18 15:12:56 [error]: at osu.Game.Rulesets.Edit.SelectionBlueprint`1.updateState()
2022-03-18 15:12:56 [error]: at osu.Game.Rulesets.Edit.SelectionBlueprint`1.set_State(SelectionState value)
2022-03-18 15:12:56 [error]: at osu.Game.Rulesets.Edit.SelectionBlueprint`1.Deselect()
2022-03-18 15:12:56 [error]: at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer`1.RemoveBlueprintFor(T item)
2022-03-18 15:12:56 [error]: at osu.Game.Screens.Edit.EditorBeatmap.UpdateState()
2022-03-18 15:12:56 [error]: at osu.Game.Screens.Edit.TransactionalCommitComponent.EndChange()
2022-03-18 15:12:56 [error]: at osu.Game.Screens.Edit.Compose.Components.EditorSelectionHandler.DeleteItems(IEnumerable`1 items)
2022-03-18 15:12:56 [error]: at osu.Game.Screens.Edit.Compose.Components.SelectionHandler`1.DeleteSelected()
2022-03-18 15:12:56 [error]: at osu.Framework.Graphics.UserInterface.Menu.DrawableMenuItem.OnClick(ClickEvent e)
2022-03-18 15:12:56 [error]: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
2022-03-18 15:12:56 [error]: at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
2022-03-18 15:12:56 [error]: at osu.Framework.Input.MouseButtonEventManager.handleClick(InputState state, List`1 targets)
2022-03-18 15:12:56 [error]: at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
2022-03-18 15:12:56 [error]: at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
2022-03-18 15:12:56 [error]: at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
2022-03-18 15:12:56 [error]: at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
2022-03-18 15:12:56 [error]: at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
2022-03-18 15:12:56 [error]: at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
2022-03-18 15:12:56 [error]: at osu.Framework.Input.StateChanges.MouseButtonInput.Apply(InputState state, IInputStateChangeHandler handler)
2022-03-18 15:12:56 [error]: at osu.Framework.Input.InputManager.Update()
2022-03-18 15:12:56 [error]: at osu.Framework.Input.PassThroughInputManager.Update()
2022-03-18 15:12:56 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-03-18 15:12:56 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-03-18 15:12:56 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2022-03-18 15:12:56 [error]: at osu.Framework.Threading.GameThread.processFrame()
2022-03-18 15:12:56 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2022-03-18 15:12:56 [verbose]: ⚠️ An unhandled error has occurred.
2022-03-18 15:12:56 [verbose]: 
2022-03-18 15:12:56 [verbose]: This error has been automatically reported to the devs.
2022-03-18 15:12:56 [verbose]: Focus contention triggered by NotificationOverlay.

```
