### ISSUE TITLE
Write the test case to check if load .ttf font works.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1317]
Heres' the callstack:
```
2022-05-14 09:58:46 [error]: An unhandled error has occurred.
2022-05-14 09:58:46 [error]: System.MissingMethodException: Method not found: 'System.Span`1<SixLabors.ImageSharp.PixelFormats.Rgba32> SixLabors.ImageSharp.ImageFrame`1.GetPixelRowSpan(Int32)'.
2022-05-14 09:58:46 [error]: at SixLabors.ImageSharp.Drawing.Processing.Processors.Drawing.FillRegionProcessor`1.OnFrameApply(ImageFrame`1 source)
2022-05-14 09:58:46 [error]: at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.IImageProcessor<TPixel>.Execute()
2022-05-14 09:58:46 [error]: at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor, Rectangle rectangle)
2022-05-14 09:58:46 [error]: at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor)
2022-05-14 09:58:46 [error]: at SixLabors.ImageSharp.Drawing.Processing.FillPathCollectionExtensions.Fill(IImageProcessingContext source, DrawingOptions options, IBrush brush, IPathCollection paths)
2022-05-14 09:58:46 [error]: at SixLabors.ImageSharp.Drawing.Processing.FillPathCollectionExtensions.Fill(IImageProcessingContext source, IBrush brush, IPathCollection paths)
2022-05-14 09:58:46 [error]: at SixLabors.ImageSharp.Drawing.Processing.FillPathCollectionExtensions.Fill(IImageProcessingContext source, Color color, IPathCollection paths)
2022-05-14 09:58:46 [error]: at osu.Game.Rulesets.Karaoke.IO.Stores.TtfGlyphStore.<>c__DisplayClass24_0.<LoadCharacter>b__0(IImageProcessingContext i)
2022-05-14 09:58:46 [error]: at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Configuration configuration, Action`1 operation)
2022-05-14 09:58:46 [error]: at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Action`1 operation)
2022-05-14 09:58:46 [error]: at osu.Game.Rulesets.Karaoke.IO.Stores.TtfGlyphStore.LoadCharacter(Char c)
2022-05-14 09:58:46 [error]: at osu.Game.Rulesets.Karaoke.IO.Stores.TtfGlyphStore.Get(String name)
2022-05-14 09:58:46 [error]: at osu.Framework.IO.Stores.ResourceStore`1.Get(String name)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Textures.TextureStore.Get(String name, WrapMode wrapModeS, WrapMode wrapModeT)
2022-05-14 09:58:46 [error]: at osu.Framework.IO.Stores.FontStore.Get(String name)
2022-05-14 09:58:46 [error]: at osu.Framework.IO.Stores.FontStore.Get(String fontName, Char character)
2022-05-14 09:58:46 [error]: at osu.Framework.IO.Stores.FontStore.Get(String fontName, Char character)
2022-05-14 09:58:46 [error]: at osu.Framework.Text.TextBuilder.getTexturedGlyph(Char character)
2022-05-14 09:58:46 [error]: at osu.Framework.Text.TextBuilder.tryCreateGlyph(Char character, TextBuilderGlyph& glyph)
2022-05-14 09:58:46 [error]: at osu.Framework.Text.TextBuilder.AddCharacter(Char character)
2022-05-14 09:58:46 [error]: at osu.Framework.Text.TextBuilder.AddText(String text)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Sprites.SpriteText.computeCharacters()
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Sprites.SpriteText.computeScreenSpaceCharacters()
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Sprites.SpriteText.SpriteTextDrawNode.ApplyState()
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Drawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
2022-05-14 09:58:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
2022-05-14 09:58:46 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2022-05-14 09:58:46 [error]: at osu.Framework.Threading.GameThread.processFrame()
2022-05-14 09:58:46 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2022-05-14 09:58:46 [verbose]: ⚠️ An unhandled error has occurred.
2022-05-14 09:58:46 [verbose]: 
2022-05-14 09:58:46 [verbose]: This error has been automatically reported to the devs.
2022-05-14 09:58:46 [verbose]: Focus contention triggered by NotificationOverlay.

```

**Comment by andy840119** [comment]
Guess it's caused by packing tool.

**Comment by andy840119** [comment]
Not really sure copy the dll can solve this issue?
```
<InputAssemblies Include="$(OutputPath)\SixLabors.Fonts.dll"/>
<InputAssemblies Include="$(OutputPath)\SixLabors.ImageSharp.Drawing.dll"/>
```
Not packing those two dlls because seems they will conflict.
Or check update the package will get help?

**Comment by andy840119** [comment]
![image](https://user-images.githubusercontent.com/9100368/168453910-0c00c6bc-22bc-4dca-97e6-330249f0706b.png)
It's not packing issue.
Has the same issue in the debug build.

**Comment by andy840119** [comment]
Should write a test case for it also.
Should check why `TtfGlyphStoreTest` is not working.

**Comment by andy840119** [comment]
Not really sure related to https://github.com/SixLabors/ImageSharp/issues/1542

**Comment by andy840119** [comment]
Notice that ImageSharp has been upgrade in the https://github.com/ppy/osu-framework/commit/2da85250a24b9871f02580984cfb5431042da082 at 2022/04/02

**Comment by andy840119** [comment]
Upgrade the package seems able to fix the issue.
The remain part is add the test case.
