### ISSUE TITLE
Fix ruby generator not work in the release build.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1319]
Here's the log:
```
2022-05-14 12:04:17 [error]: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
2022-05-14 12:04:17 [error]: ---> System.IO.FileNotFoundException: Could not load file or assembly 'Lucene.Net, Version=4.0.0.0, Culture=neutral, PublicKeyToken=85089178b9ac3181'. 指定されたファイルが見つかりません。
2022-05-14 12:04:17 [error]: File name: 'Lucene.Net, Version=4.0.0.0, Culture=neutral, PublicKeyToken=85089178b9ac3181'
2022-05-14 12:04:17 [error]: at osu.Game.Rulesets.Karaoke.Edit.Generator.RubyTags.Ja.JaRubyTagGenerator..ctor(JaRubyTagGeneratorConfig config)
2022-05-14 12:04:17 [error]: --- End of inner exception stack trace ---
2022-05-14 12:04:17 [error]: at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2022-05-14 12:04:17 [error]: at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2022-05-14 12:04:17 [error]: at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
2022-05-14 12:04:17 [error]: at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
2022-05-14 12:04:17 [error]: at System.Activator.CreateInstance(Type type, Object[] args)
2022-05-14 12:04:17 [error]: at osu.Game.Rulesets.Karaoke.Edit.Generator.GeneratorSelector`2.<>c__DisplayClass5_0`2.<RegisterGenerator>b__0()
2022-05-14 12:04:17 [error]: at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2022-05-14 12:04:17 [error]: at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2022-05-14 12:04:17 [error]: at System.Lazy`1.CreateValue()
2022-05-14 12:04:17 [error]: at osu.Game.Rulesets.Karaoke.Edit.Generator.RubyTags.RubyTagGeneratorSelector.GenerateRubyTags(Lyric lyric)
2022-05-14 12:04:17 [error]: at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.Lyrics.LyricRubyTagsChangeHandler.<AutoGenerate>b__2_0(Lyric lyric)
2022-05-14 12:04:17 [error]: at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.HitObjectChangeHandler`1.<>c__DisplayClass7_0.<PerformOnSelection>b__0(HitObject h)
2022-05-14 12:04:17 [error]: at osu.Game.Screens.Edit.EditorBeatmap.PerformOnSelection(Action`1 action)
2022-05-14 12:04:17 [error]: at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.HitObjectChangeHandler`1.PerformOnSelection(Action`1 action)
2022-05-14 12:04:17 [error]: at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.Lyrics.LyricRubyTagsChangeHandler.AutoGenerate()
2022-05-14 12:04:17 [error]: at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Extends.RubyRomaji.RubyTagAutoGenerateSection.RubyTagAutoGenerateSubsection.Apply()
2022-05-14 12:04:17 [error]: at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Extends.Components.AutoGenerateSubsection.<>c__DisplayClass1_0.<load>b__1(LyricEditorSelectingAction e)
2022-05-14 12:04:17 [error]: at osu.Game.Rulesets.Karaoke.Edit.Lyrics.States.LyricSelectionState.EndSelecting(LyricEditorSelectingAction action)
2022-05-14 12:04:17 [error]: at osu.Game.Rulesets.Karaoke.Edit.Lyrics.ApplySelectingArea.<>c__DisplayClass5_0.<load>b__2()
2022-05-14 12:04:17 [error]: at osu.Framework.Graphics.Containers.ClickableContainer.OnClick(ClickEvent e)
2022-05-14 12:04:17 [error]: at osu.Game.Graphics.UserInterface.OsuButton.OnClick(ClickEvent e)
2022-05-14 12:04:17 [error]: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
2022-05-14 12:04:17 [error]: at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
2022-05-14 12:04:17 [error]: at osu.Framework.Input.MouseButtonEventManager.handleClick(InputState state, List`1 targets)
2022-05-14 12:04:17 [error]: at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
2022-05-14 12:04:17 [error]: at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
2022-05-14 12:04:17 [error]: at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
2022-05-14 12:04:17 [error]: at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
2022-05-14 12:04:17 [error]: at osu.Framework.Input.InputManager.Update()
2022-05-14 12:04:17 [error]: at osu.Framework.Input.PassThroughInputManager.Update()
2022-05-14 12:04:17 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-05-14 12:04:17 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-14 12:04:17 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2022-05-14 12:04:17 [error]: at osu.Framework.Threading.GameThread.processFrame()
2022-05-14 12:04:17 [error]: An unhandled error has occurred. (inner)
2022-05-14 12:04:17 [error]: System.IO.FileNotFoundException: Could not load file or assembly 'Lucene.Net, Version=4.0.0.0, Culture=neutral, PublicKeyToken=85089178b9ac3181'. 指定されたファイルが見つかりません。
2022-05-14 12:04:17 [error]: File name: 'Lucene.Net, Version=4.0.0.0, Culture=neutral, PublicKeyToken=85089178b9ac3181'
2022-05-14 12:04:17 [error]: at osu.Game.Rulesets.Karaoke.Edit.Generator.RubyTags.Ja.JaRubyTagGenerator..ctor(JaRubyTagGeneratorConfig config)
2022-05-14 12:04:17 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2022-05-14 12:04:17 [verbose]: ⚠️ An unhandled error has occurred.
2022-05-14 12:04:17 [verbose]: 
2022-05-14 12:04:17 [verbose]: This error has been automatically reported to the devs.
2022-05-14 12:04:17 [verbose]: ⚠️ An unhandled error has occurred. (inner)
2022-05-14 12:04:17 [verbose]: 
2022-05-14 12:04:17 [verbose]: This error has been automatically reported to the devs.
```

**Comment by andy840119** [comment]
Guess it's caused by packing tool.
Or did i missing packing it?

**Comment by andy840119** [comment]
Should be works now.
