### ISSUE TITLE
Fix cannot show the edit note mode if use legacy skin.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1331]
Guess it's caused by missing the note skin.

Here's the log:
```
2022-05-22 05:31:13 [error]: osu.Game.Skinning.UnsupportedSkinComponentException: Unsupported component type: osu.Game.Rulesets.Karaoke.KaraokeSkinComponent (lookup: "Gameplay/karaoke/note").
2022-05-22 05:31:13 [error]: at osu.Game.Skinning.LegacySkin.GetDrawableComponent(ISkinComponent component) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Skinning/LegacySkin.cs:line 399
2022-05-22 05:31:13 [error]: at osu.Game.Skinning.SkinManager.lookupWithFallback[T](Func`2 lookupFunction) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Skinning/SkinManager.cs:line 242
2022-05-22 05:31:13 [error]: at osu.Game.Skinning.SkinnableDrawable.SkinChanged(ISkinSource skin) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Skinning/SkinnableDrawable.cs:line 101
2022-05-22 05:31:13 [error]: at osu.Game.Skinning.SkinReloadableDrawable.LoadAsyncComplete() in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Skinning/SkinReloadableDrawable.cs:line 41
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-05-22 05:31:13 [error]: --- End of stack trace from previous location ---
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.LoadFromAsync(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadComponents[TLoadable](List`1 components, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext, CancellationToken cancellation)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.LoadComponents[TLoadable](IEnumerable`1 components)
2022-05-22 05:31:13 [error]: --- End of stack trace from previous location ---
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-05-22 05:31:13 [error]: --- End of stack trace from previous location ---
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-05-22 05:31:13 [error]: --- End of stack trace from previous location ---
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-05-22 05:31:13 [error]: --- End of stack trace from previous location ---
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-05-22 05:31:13 [error]: --- End of stack trace from previous location ---
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-05-22 05:31:13 [error]: --- End of stack trace from previous location ---
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.GridContainer.layoutContent()
2022-05-22 05:31:13 [error]: --- End of stack trace from previous location ---
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.Container`1.AddInternal(Drawable drawable)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddRangeInternal(IEnumerable`1 range)
2022-05-22 05:31:13 [error]: at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Rows.Extends.EditRowExtend.load(OsuColour colours)
2022-05-22 05:31:13 [error]: --- End of stack trace from previous location ---
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.Container`1.AddInternal(Drawable drawable)
2022-05-22 05:31:13 [error]: at osu.Game.Rulesets.Karaoke.Edit.Lyrics.DrawableLyricEditListItem.<>c__DisplayClass14_0.<.ctor>b__5()
2022-05-22 05:31:13 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2022-05-22 05:31:13 [error]: at osu.Framework.Threading.Scheduler.Update()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-05-22 05:31:13 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2022-05-22 05:31:13 [error]: at osu.Framework.Threading.GameThread.processFrame()
2022-05-22 05:31:13 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2022-05-22 05:31:13 [verbose]: ⚠️ An unhandled error has occurred.
2022-05-22 05:31:13 [verbose]: 
2022-05-22 05:31:13 [verbose]: This error has been automatically reported to the devs.
2022-05-22 05:31:13 [verbose]: Focus contention triggered by NotificationOverlay.
2022-05-22 05:31:14 [verbose]: 📺 BackgroundScreenStack#201(depth:2) exit from BackgroundScreenBeatmap#147
2022-05-22 05:31:14 [verbose]: 📺 BackgroundScreenStack#201(depth:2) resume to BackgroundScreenBeatmap#226
2022-05-22 05:31:14 [verbose]: 📺 OsuScreenStack#256(depth:7) exit from KaraokeEditor#328
2022-05-22 05:31:14 [verbose]: 📺 OsuScreenStack#256(depth:7) resume to Editor#350
2022-05-22 05:31:15 [verbose]: Invalidating working beatmap cache for 森田交一 - Shinning star (andy840119) [Normal]
2022-05-22 05:31:15 [verbose]: Editor providing re-fetched beatmap post edit session
2022-05-22 05:31:15 [verbose]: Game-wide working beatmap updated to 森田交一 - Shinning star (andy840119) [Normal]
2022-05-22 05:31:15 [verbose]: 📺 OsuScreenStack#256(depth:6) exit from Editor#350
2022-05-22 05:31:15 [verbose]: 📺 OsuScreenStack#256(depth:6) resume to EditorLoader#519
2022-05-22 05:31:15 [verbose]: 📺 OsuScreenStack#256(depth:5) exit from EditorLoader#519
2022-05-22 05:31:15 [verbose]: 📺 OsuScreenStack#256(depth:5) resume to PlaySongSelect#121
2022-05-22 05:31:16 [verbose]: 📺 BackgroundScreenStack#201(depth:1) exit from BackgroundScreenBeatmap#226
2022-05-22 05:31:16 [verbose]: 📺 BackgroundScreenStack#201(depth:1) resume to BackgroundScreenDefault#605
2022-05-22 05:31:16 [verbose]: 📺 OsuScreenStack#256(depth:4) exit from PlaySongSelect#121
2022-05-22 05:31:16 [verbose]: 📺 OsuScreenStack#256(depth:4) resume to MainMenu#505
2022-05-22 05:31:16 [verbose]: decoupled ruleset transferred ("" -> "karaoke!")
2022-05-22 05:31:16 [verbose]: ButtonSystem's state changed from EnteringMode to TopLevel
2022-05-22 05:31:22 [verbose]: Chat is now polling every 600000 ms
2022-05-22 05:31:22 [verbose]: ButtonSystem's state changed from TopLevel to Initial
2022-05-22 05:31:46 [verbose]: Chat is now polling every 60000 ms
2022-05-22 05:31:57 [verbose]: Chat is now polling every 600000 ms

```

**Comment by andy840119** [comment]
Note:
Maybe should make the skin provider for lyric editor only.
And this skin should cover to the note part.
