### ISSUE TITLE
`Children cannot be cleared on a disposed drawable.` exception in the import lyric screen.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1348]
Here's the log:
```
System.ObjectDisposedException: Children cannot be cleared on a disposed drawable.
Object name: 'GenerateRubyRomajiNavigation+GenerateRubyTextFlowContainer'.
   at osu.Framework.Graphics.Containers.CompositeDrawable.ClearInternal(Boolean disposeChildren)
   at osu.Framework.Graphics.Containers.FlowContainer`1.ClearInternal(Boolean disposeChildren)
   at osu.Framework.Graphics.Containers.Container`1.Clear(Boolean disposeChildren)
   at osu.Framework.Graphics.Containers.TextFlowContainer.Clear(Boolean disposeChildren)
   at osu.Framework.Graphics.Containers.Container`1.Clear()
   at osu.Framework.Graphics.Containers.TextFlowContainer.set_Text(LocalisableString value)
   at osu.Game.Rulesets.Karaoke.Edit.ImportLyric.TopNavigation.updateNavigationDisplayInfo(NavigationState value) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/ImportLyric/TopNavigation.cs:line 140
   at osu.Game.Rulesets.Karaoke.Edit.ImportLyric.TopNavigation.TriggerStateChange() in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/ImportLyric/TopNavigation.cs:line 95
   at osu.Game.Screens.Edit.TransactionalCommitComponent.EndChange()
   at osu.Game.Screens.Edit.EditorBeatmap.PerformOnSelection(Action`1 action)
   at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.HitObjectChangeHandler`1.PerformOnSelection(Action`1 action) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/ChangeHandlers/HitObjectChangeHandler.cs:line 47
   at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.Lyrics.LyricLanguageChangeHandler.AutoGenerate() in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/ChangeHandlers/Lyrics/LyricLanguageChangeHandler.cs:line 23
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Extends.Languages.LanguageAutoGenerateSubsection.Apply() in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/Lyrics/Extends/Languages/LanguageAutoGenerateSubsection.cs:line 25
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Extends.Components.AutoGenerateSubsection.<>c__DisplayClass1_0.<load>b__1(LyricEditorSelectingAction e) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/Lyrics/Extends/Components/AutoGenerateSubsection.cs:line 93
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.States.LyricSelectionState.EndSelecting(LyricEditorSelectingAction action) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/Lyrics/States/LyricSelectionState.cs:line 54
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.ApplySelectingArea.<>c__DisplayClass5_0.<load>b__2() in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/Lyrics/ApplySelectingArea.cs:line 81
   at osu.Framework.Graphics.Containers.ClickableContainer.OnClick(ClickEvent e)
   at osu.Game.Graphics.UserInterface.OsuButton.OnClick(ClickEvent e)
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at osu.Framework.Input.ButtonEventManager`1.<>c__DisplayClass14_0.<PropagateButtonEvent>b__0(Drawable target)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.MouseButtonEventManager.handleClick(InputState state, List`1 targets)
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
   at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.StateChanges.MouseButtonInput.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.PassThroughInputManager.Handle(UIEvent e)
   at osu.Framework.Graphics.Drawable.OnMouseUp(MouseUpEvent e)
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at osu.Framework.Input.ButtonEventManager`1.<>c__DisplayClass14_0.<PropagateButtonEvent>b__0(Drawable target)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
   at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.StateChanges.MouseButtonInput.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.InputManager.Update()
   at osu.Framework.Input.PassThroughInputManager.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.processFrame()
```

**Comment by andy840119** [comment]
Fixed.
