### ISSUE TITLE
Fix select language might cause error in the selecting language step in the lyric importer.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1349]
here's the log:
```
System.NotSupportedException: Cannot trigger the change while applying another change.
   at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.HitObjectChangeHandler`1.PerformOnSelection(Action`1 action) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/ChangeHandlers/HitObjectChangeHandler.cs:line 38
   at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.Lyrics.LyricLanguageChangeHandler.SetLanguage(CultureInfo language) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/ChangeHandlers/Lyrics/LyricLanguageChangeHandler.cs:line 32
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Rows.Components.SubInfo.LanguageInfo.<>c__DisplayClass2_0.<load>b__0(ValueChangedEvent`1 value) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/Lyrics/Rows/Components/SubInfo/LanguageInfo.cs:line 46
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
   at osu.Framework.Bindables.Bindable`1.set_Value(T value)
   at osu.Game.Rulesets.Karaoke.Objects.Lyric.set_Language(CultureInfo value) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Objects/Lyric.cs:line 173
   at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.Lyrics.LyricLanguageChangeHandler.<>c__DisplayClass5_0.<SetLanguage>b__0(Lyric lyric) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/ChangeHandlers/Lyrics/LyricLanguageChangeHandler.cs:line 37
   at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.HitObjectChangeHandler`1.<>c__DisplayClass9_0.<PerformOnSelection>b__0(HitObject h) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/ChangeHandlers/HitObjectChangeHandler.cs:line 50
   at osu.Game.Screens.Edit.EditorBeatmap.PerformOnSelection(Action`1 action)
   at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.HitObjectChangeHandler`1.PerformOnSelection(Action`1 action) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/ChangeHandlers/HitObjectChangeHandler.cs:line 47
   at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.Lyrics.LyricLanguageChangeHandler.SetLanguage(CultureInfo language) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/ChangeHandlers/Lyrics/LyricLanguageChangeHandler.cs:line 32
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Rows.Components.SubInfo.LanguageInfo.<>c__DisplayClass2_0.<load>b__0(ValueChangedEvent`1 value) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/Lyrics/Rows/Components/SubInfo/LanguageInfo.cs:line 46
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
   at osu.Framework.Bindables.Bindable`1.set_Value(T value)
   at osu.Game.Rulesets.Karaoke.Graphics.UserInterfaceV2.LanguageSelector.<.ctor>b__4_2(CultureInfo item) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Graphics/UserInterfaceV2/LanguageSelector.cs:line 58
   at osu.Game.Rulesets.Karaoke.Graphics.UserInterface.RearrangeableTextFlowListContainer`1.<CreateOsuDrawable>b__5_1(TModel set) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Graphics/UserInterface/RearrangeableTextFlowListContainer.cs:line 47
   at osu.Game.Rulesets.Karaoke.Graphics.UserInterface.RearrangeableTextFlowListContainer`1.DrawableTextListItem.OnClick(ClickEvent e) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Graphics/UserInterface/RearrangeableTextFlowListContainer.cs:line 99
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at osu.Framework.Input.ButtonEventManager`1.<>c__DisplayClass14_0.<PropagateButtonEvent>b__0(Drawable target)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.MouseButtonEventManager.handleClick(InputState state, List`1 targets)
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
   at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.StateChanges.MouseButtonInput.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.PassThroughInputManager.Handle(UIEvent e)
   at osu.Framework.Graphics.Drawable.OnMouseUp(MouseUpEvent e)
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at osu.Framework.Input.ButtonEventManager`1.<>c__DisplayClass14_0.<PropagateButtonEvent>b__0(Drawable target)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
   at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.StateChanges.MouseButtonInput.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.InputManager.Update()
   at osu.Framework.Input.PassThroughInputManager.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.processFrame()
```

Caused due to selected lyric not being cleaned in another import step.
Guess should choose a way to fix this issue:
1. give the select language mode a caret.
2. should reset the caret after exit or enter.

**Comment by andy840119** [comment]
Fixed.
