### ISSUE TITLE
Fix got crash while generating the ruby.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1353]
Only cause when lyric has no timed time-tag.

Here's the log:
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'rubyTag')
   at osu.Framework.Graphics.Sprites.LyricSpriteText.GetRubyTagDrawRectangle(PositionText rubyTag, Boolean drawSizeOnly)
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Rows.Components.EditorKaraokeSpriteText.EditorLyricSpriteText.GetRubyTagPosition(RubyTag rubyTag) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/Lyrics/Rows/Components/EditorKaraokeSpriteText.cs:line 167
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Rows.Components.EditorKaraokeSpriteText.GetTextTagPosition(ITextTag textTag) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/Lyrics/Rows/Components/EditorKaraokeSpriteText.cs:line 95
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Rows.Components.Blueprints.TextTagSelectionBlueprint`1.<UpdatePositionAndSize>b__10_0() in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/Lyrics/Rows/Components/Blueprints/TextTagSelectionBlueprint.cs:line 75
   at osu.Framework.Threading.ScheduledDelegate.InvokeTask()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
...
```

**Comment by andy840119** [comment]
Caused after `RubyTagSelectionBlueprint` loaded.

**Comment by andy840119** [comment]
Implemented.
