### ISSUE TITLE
Fix cannot switch to edit note mode if use the classic skin.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1435]
Should wrap the editor skin for the note area.

Here's the fucking log:
```
osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-07-12 14:14:57 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-07-12 14:14:57 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-07-12 14:14:57 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-07-12 14:14:57 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.GridContainer.layoutContent()
2022-07-12 14:14:57 [error]: --- End of stack trace from previous location ---
2022-07-12 14:14:57 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-07-12 14:14:57 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.Container`1.AddInternal(Drawable drawable)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddRangeInternal(IEnumerable`1 range)
2022-07-12 14:14:57 [error]: at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Rows.Extends.EditRowExtend.load(ILyricEditorState state, LyricEditorColourProvider colourProvider)
2022-07-12 14:14:57 [error]: --- End of stack trace from previous location ---
2022-07-12 14:14:57 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-07-12 14:14:57 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-07-12 14:14:57 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.Container`1.AddInternal(Drawable drawable)
2022-07-12 14:14:57 [error]: at osu.Game.Rulesets.Karaoke.Edit.Lyrics.DrawableLyricEditListItem.<>c__DisplayClass14_0.<.ctor>b__5()
2022-07-12 14:14:57 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2022-07-12 14:14:57 [error]: at osu.Framework.Threading.Scheduler.Update()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-12 14:14:57 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2022-07-12 14:14:57 [error]: at osu.Framework.Threading.GameThread.processFrame()

```

**Comment by andy840119** [comment]
Also, has load skin issue while entry the lyric editor:
```
2022-07-12 14:18:36 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2022-07-12 14:18:36 [error]: at osu.Game.Rulesets.Karaoke.Skinning.KaraokeSkin.GetElementStringContentFromSkinInfo(SkinInfo skinInfo, String filename)
2022-07-12 14:18:36 [error]: at osu.Game.Rulesets.Karaoke.Skinning.KaraokeSkin.<.ctor>b__4_0(SkinInfo s)
```
