### ISSUE TITLE
Fix will cause crash if switch from translate screen to singer screen.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1436]
Only caused due to switch to another screen if focus on the textbox.

Here's the callstack:
```
System.InvalidOperationException: Should be exactly one THitObject being selected.
   at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.HitObjectChangeHandler`1.CheckExactlySelectedOneHitObject() in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/ChangeHandlers/HitObjectChangeHandler.cs:line 33
   at osu.Game.Rulesets.Karaoke.Edit.ChangeHandlers.Lyrics.LyricTranslateChangeHandler.UpdateTranslate(CultureInfo cultureInfo, String translate) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/ChangeHandlers/Lyrics/LyricTranslateChangeHandler.cs:line 14
   at osu.Game.Rulesets.Karaoke.Edit.Translate.Components.LyricTranslateTextBox.<>c__DisplayClass14_0.<.ctor>b__1(TextBox t, Boolean _) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/Translate/Components/LyricTranslateTextBox.cs:line 56
   at osu.Framework.Graphics.UserInterface.TextBox.Commit()
   at osu.Framework.Graphics.UserInterface.TextBox.OnFocusLost(FocusLostEvent e)
   at osu.Framework.Graphics.UserInterface.BasicTextBox.OnFocusLost(FocusLostEvent e)
   at osu.Game.Graphics.UserInterface.OsuTextBox.OnFocusLost(FocusLostEvent e)
   at osu.Game.Rulesets.Karaoke.Edit.Translate.Components.LyricTranslateTextBox.OnFocusLost(FocusLostEvent e) in /Volumes/Data/Github/karaoke-dev/karaoke/osu.Game.Rulesets.Karaoke/Edit/Translate/Components/LyricTranslateTextBox.cs:line 74
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at osu.Framework.Input.InputManager.ChangeFocus(Drawable potentialFocusTarget, InputState state)
   at osu.Framework.Input.InputManager.ChangeFocus(Drawable potentialFocusTarget)
   at osu.Framework.Input.InputManager.ChangeFocusFromClick(Drawable clickedDrawable)
   at osu.Framework.Input.MouseButtonEventManager.handleClick(InputState state, List`1 targets)
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
   at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.StateChanges.MouseButtonInput.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.PassThroughInputManager.Handle(UIEvent e)
   at osu.Framework.Graphics.Drawable.OnMouseUp(MouseUpEvent e)
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at osu.Framework.Input.ButtonEventManager`1.<>c__DisplayClass14_0.<PropagateButtonEvent>b__0(Drawable target)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
   at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.StateChanges.MouseButtonInput.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.InputManager.Update()
   at osu.Framework.Input.PassThroughInputManager.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.processFrame()
```

**Comment by andy840119** [comment]
Another issue:
Should not call the change handler if text not edited.

**Comment by andy840119** [comment]
Guess fixed.
