### ISSUE TITLE
Fix cannot import the lyric due to missing depenedency

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1510]
Here's the log:
```
2022-08-13 15:47:02 [error]: osu.Framework.Allocation.DependencyNotRegisteredException: The type LyricEditorClipboard has a dependency on ILyricLanguageChangeHandler, but the dependency is not registered.
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.ResolvedAttribute.<>c__DisplayClass7_0.<getDependency>b__0(IReadOnlyDependencyContainer dc)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.ResolvedAttribute.<>c__DisplayClass6_1.<CreateActivator>b__2(Object target, IReadOnlyDependencyContainer dc)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.ResolvedAttribute.<>c__DisplayClass6_0.<CreateActivator>b__1(Object target, IReadOnlyDependencyContainer dc)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-08-13 15:47:02 [error]: --- End of stack trace from previous location ---
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-08-13 15:47:02 [error]: --- End of stack trace from previous location ---
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.GridContainer.layoutContent()
2022-08-13 15:47:02 [error]: --- End of stack trace from previous location ---
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-08-13 15:47:02 [error]: --- End of stack trace from previous location ---
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Drawable.LoadFromAsync(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadComponents[TLoadable](List`1 components, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext, CancellationToken cancellation)
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass17_0`1.<LoadComponentsAsync>b__1()
2022-08-13 15:47:02 [error]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2022-08-13 15:47:02 [error]: --- End of stack trace from previous location ---
2022-08-13 15:47:02 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2022-08-13 15:47:02 [error]: --- End of stack trace from previous location ---
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass17_2`1.<LoadComponentsAsync>b__4()
2022-08-13 15:47:02 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2022-08-13 15:47:02 [error]: at osu.Framework.Threading.Scheduler.Update()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-08-13 15:47:02 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2022-08-13 15:47:02 [error]: at osu.Framework.Threading.GameThread.processFrame()
2022-08-13 15:47:02 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2022-08-13 15:47:02 [verbose]: ⚠️ An unhandled error has occurred.
2022-08-13 15:47:02 [verbose]: 
2022-08-13 15:47:02 [verbose]: This error has been automatically reported to the devs.
2022-08-13 15:47:25 [verbose]: Chat is now polling every 600000 ms
2022-08-13 15:47:26 [verbose]: Chat is now polling every 60000 ms
2022-08-13 15:47:33 [verbose]: Chat is now polling every 600000 ms
```

**Comment by andy840119** [comment]
Got no damn idea why there's no CI error in the test case.

**Comment by andy840119** [comment]
Note:
Should not use the `AllowNull` attribute because the injection might get the null value if cannot get the dependency in the debug build(same as `[Resolved(CanBeNull = true)]`)
But it will get the error in the release build.

**Comment by andy840119** [comment]
Seems should mark some of the change handlers as nullable.
And should throw the exception if the change handler is null.

**Comment by andy840119** [comment]
Tested, still have the same issue in the https://github.com/karaoke-dev/karaoke/releases/tag/2022.0814.0.

**Comment by andy840119** [comment]
Need to check if the same issue will happened in the osx

[update]
got the same issue in the osx.

**Comment by andy840119** [comment]
Need to check is caused by irmerge or not?

**Comment by andy840119** [comment]
Guess this issue is outdated?
As i remember, it's possible to import the lyric in the karaoke beatmap editor.
