### ISSUE TITLE
Fix got the error if switch from typing mode into split text mode in the lyric editor.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1649]
Guess caused by #1643
Happened because caret and bindable caret does not the same type.

Here's the log:
```
System.InvalidCastException: Specified cast is not valid.
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Components.Lyrics.Carets.DrawableCaret`1.<>c__DisplayClass2_0.<load>b__0(ValueChangedEvent`1 e) in D:\Github\karaoke-dev\karaoke\osu.Game.Rulesets.Karaoke\Edit\Lyrics\Components\Lyrics\Carets\DrawableCaret.cs:line 43
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
   at osu.Framework.Bindables.Bindable`1.set_Value(T value)
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.States.LyricCaretState.refreshAlgorithmAndCaretPosition() in D:\Github\karaoke-dev\karaoke\osu.Game.Rulesets.Karaoke\Edit\Lyrics\States\LyricCaretState.cs:line 103
   at osu.Framework.Threading.ScheduledDelegate.InvokeTask()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
...
```

**Comment by andy840119** [comment]
Have no idea why not happened if switching between `TimeTagIndexCaretPositionAlgorithm` and `TimeTagCaretPositionAlgorithm` in the `LyricCaretState`.

**Comment by andy840119** [comment]
Guess should be fixed.
