### ISSUE TITLE
Fix the `dependency is not registered` issue even if variable is nullable

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1672]
https://github.com/karaoke-dev/karaoke/blob/15e42b1a41b729e211543ce8e805c369ffe93ace/osu.Game.Rulesets.Karaoke/Edit/ChangeHandlers/HitObjectChangeHandler.cs#L27
This dependency is mark as nullable, means it accept the null case.
But it will got the error only in the release build.

Not really sure it's caused by the packing tool.

here's the log:
```
2022-10-22 03:28:39 [error]: osu.Framework.Allocation.DependencyNotRegisteredException: The type HitObjectChangeHandler<Lyric> has a dependency on IEditorChangeHandler, but the dependency is not registered.
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.ResolvedAttribute.<>c__DisplayClass7_0.<getDependency>b__0(IReadOnlyDependencyContainer dc)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.ResolvedAttribute.<>c__DisplayClass6_1.<CreateActivator>b__2(Object target, IReadOnlyDependencyContainer dc)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.ResolvedAttribute.<>c__DisplayClass6_0.<CreateActivator>b__1(Object target, IReadOnlyDependencyContainer dc)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-10-22 03:28:39 [error]: --- End of stack trace from previous location ---
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-10-22 03:28:39 [error]: --- End of stack trace from previous location ---
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-10-22 03:28:39 [error]: --- End of stack trace from previous location ---
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-10-22 03:28:39 [error]: --- End of stack trace from previous location ---
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Drawable.LoadFromAsync(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadComponents[TLoadable](List`1 components, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext, CancellationToken cancellation)
2022-10-22 03:28:39 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass13_0`1.<LoadComponentsAsync>b__1()
2022-10-22 03:28:39 [error]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by andy840119** [comment]
Mark as related to the #1510.

**Comment by andy840119** [comment]
Guess this issue can be closed due to found the root cause.
It's caused by ILMerge tool.
