### ISSUE TITLE
Fix delete all ruby text will cause exception.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1732]
Here's the callstack:
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'rubyTag')
   at osu.Framework.Graphics.Sprites.LyricSpriteText.GetRubyTagDrawRectangle(PositionText rubyTag, Boolean drawSizeOnly)
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Components.Lyrics.InteractableKaraokeSpriteText.EditorLyricSpriteText.GetRubyTagPosition(RubyTag rubyTag) in D:\Github\karaoke-dev\karaoke\osu.Game.Rulesets.Karaoke\Edit\Lyrics\Components\Lyrics\InteractableKaraokeSpriteText.cs:line 204
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Components.Lyrics.InteractableKaraokeSpriteText.GetTextTagPosition(ITextTag textTag) in D:\Github\karaoke-dev\karaoke\osu.Game.Rulesets.Karaoke\Edit\Lyrics\Components\Lyrics\InteractableKaraokeSpriteText.cs:line 99
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Components.Lyrics.Blueprints.TextTagSelectionBlueprint`1.<UpdatePositionAndSize>b__10_0() in D:\Github\karaoke-dev\karaoke\osu.Game.Rulesets.Karaoke\Edit\Lyrics\Components\Lyrics\Blueprints\TextTagSelectionBlueprint.cs:line 77
   at osu.Framework.Threading.ScheduledDelegate.InvokeTask()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
   ...
   at osu.Framework.Testing.TestBrowser.ErrorCatchingDelayedLoadWrapper.UpdateSubTree()
```

**Comment by andy840119** [comment]
Fixed.
