### ISSUE TITLE
Fix cannot entry to the gameplay.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1941]
Here's the log:
```
2023-04-19 15:20:40 [error]: System.InvalidOperationException: Can't use Value on managed objects from non-update threads
2023-04-19 15:20:40 [error]: at osu.Game.Database.RealmLive`1.get_Value() in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Database/RealmLive.cs:line 125
2023-04-19 15:20:40 [error]: at osu.Game.Rulesets.Karaoke.Skinning.Legacy.KaraokeLegacySkinTransformer.<GetDrawableComponent>g__getTargetComponentsContainerFromOtherPlace|3_0(<>c__DisplayClass3_0& )
2023-04-19 15:20:40 [error]: at osu.Game.Rulesets.Karaoke.Skinning.Legacy.KaraokeLegacySkinTransformer.GetDrawableComponent(ISkinComponentLookup lookup)
2023-04-19 15:20:40 [error]: at osu.Game.Skinning.SkinProvidingContainer.GetDrawableComponent(ISkinComponentLookup lookup) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Skinning/SkinProvidingContainer.cs:line 117
2023-04-19 15:20:40 [error]: at osu.Game.Skinning.SkinComponentsContainer.Reload() in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Skinning/SkinComponentsContainer.cs:line 61
2023-04-19 15:20:40 [error]: at osu.Game.Skinning.SkinComponentsContainer.SkinChanged(ISkinSource skin) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Skinning/SkinComponentsContainer.cs:line 119
2023-04-19 15:20:40 [error]: at osu.Game.Skinning.SkinReloadableDrawable.skinChanged() in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Skinning/SkinReloadableDrawable.cs:line 85
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<RegisterForDependencyActivation>b__202_0(Object t, IReadOnlyDependencyContainer d)
2023-04-19 15:20:40 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2023-04-19 15:20:40 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2023-04-19 15:20:40 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2023-04-19 15:20:40 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2023-04-19 15:20:40 [error]: at osu.Framework.Allocation.DependencyActivator.Activate[T](T obj, IReadOnlyDependencyContainer dependencies)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<RegisterForDependencyActivation>b__202_0(Object t, IReadOnlyDependencyContainer d)
2023-04-19 15:20:40 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2023-04-19 15:20:40 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2023-04-19 15:20:40 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2023-04-19 15:20:40 [error]: at osu.Framework.Allocation.DependencyActivator.Activate[T](T obj, IReadOnlyDependencyContainer dependencies)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.Container`1.AddInternal(Drawable drawable)
2023-04-19 15:20:40 [error]: at osu.Game.Screens.Play.Player.load(AudioManager audio, OsuConfigManager config, OsuGameBase game, CancellationToken cancellationToken) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Screens/Play/Player.cs:line 318
2023-04-19 15:20:40 [error]: at osu.Game.Screens.Play.Player.<>c.<RegisterForDependencyActivation>b__159_0(Object t, IReadOnlyDependencyContainer d) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/osu.Framework.SourceGeneration/osu.Framework.SourceGeneration.DependencyInjectionSourceGenerator/g_osu.Game.Screens.Play.Player_Dependencies.cs:line 19
2023-04-19 15:20:40 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2023-04-19 15:20:40 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2023-04-19 15:20:40 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2023-04-19 15:20:40 [error]: at osu.Framework.Allocation.DependencyActivator.Activate[T](T obj, IReadOnlyDependencyContainer dependencies)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Drawable.LoadFromAsync(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadComponents[TLoadable](List`1 components, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext, CancellationToken cancellation)
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass13_0`1.<LoadComponentsAsync>b__1()
2023-04-19 15:20:40 [error]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2023-04-19 15:20:40 [error]: --- End of stack trace from previous location ---
2023-04-19 15:20:40 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2023-04-19 15:20:40 [error]: --- End of stack trace from previous location ---
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass13_2`1.<LoadComponentsAsync>b__4()
2023-04-19 15:20:40 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2023-04-19 15:20:40 [error]: at osu.Framework.Threading.Scheduler.Update()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-04-19 15:20:40 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2023-04-19 15:20:40 [error]: at osu.Framework.Threading.GameThread.processFrame()
```

**Comment by andy840119** [comment]
Note:
Caused only if using the legacy skin.

**Comment by andy840119** [comment]
This issue can be closed.
