### ISSUE TITLE
Cause error if move lyric time.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#396]
![image](https://user-images.githubusercontent.com/9100368/104119101-bdc24480-5370-11eb-88b5-a8f17f150462.png)
Cause error if move lyric time in editor.
Not really sure why but seems need to be fixed.

Call sack : 
```
   at osu.Game.Rulesets.Karaoke.UI.Components.SaitenVisualization.Add(KaraokeReplayFrame frame) in F:\Github\osu-Karaoke\osu-Karaoke-release\osu.Game.Rulesets.Karaoke\UI\Components\SaitenVisualization.cs:line 108
   at osu.Game.Rulesets.Karaoke.UI.NotePlayfield.AddReplay(KaraokeReplayFrame frame) in F:\Github\osu-Karaoke\osu-Karaoke-release\osu.Game.Rulesets.Karaoke\UI\NotePlayfield.cs:line 259
   at osu.Game.Rulesets.Karaoke.Mods.KaraokeModAutoplay.ApplyToDrawableRuleset(DrawableRuleset`1 drawableRuleset) in F:\Github\osu-Karaoke\osu-Karaoke-release\osu.Game.Rulesets.Karaoke\Mods\KaraokeModAutoplay.cs:line 42
   at osu.Game.Rulesets.UI.DrawableRuleset`1.applyRulesetMods(IReadOnlyList`1 mods, OsuConfigManager config)
   at osu.Game.Rulesets.UI.DrawableRuleset`1.RegenerateAutoplay()
   at osu.Game.Rulesets.Edit.DrawableEditRulesetWrapper`1.updateReplay()
   at osu.Game.Screens.Edit.EditorChangeHandler.UpdateState()
   at osu.Game.Screens.Edit.TransactionalCommitComponent.EndChange()
   at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer.OnDragEnd(DragEndEvent e)
   at osu.Game.Screens.Edit.Compose.Components.Timeline.TimelineBlueprintContainer.OnDragEnd(DragEndEvent e)
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.MouseButtonEventManager.handleDragEnd(InputState state)
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.PassThroughInputManager.Handle(UIEvent e)
   at osu.Framework.Graphics.Drawable.OnMouseUp(MouseUpEvent e)
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.InputManager.Update()
   at osu.Framework.Input.PassThroughInputManager.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
```

**Comment by andy840119** [comment]
Guess need to check some code about saiten written before.

**Comment by andy840119** [comment]
Also need to check why this function has been called if change lyric time.

**Comment by andy840119** [comment]
It'll cause error even if move note's time.

**Comment by andy840119** [comment]
Guess should up this issue and make a fix ASAP.
Need to check why this shit works in edit mode.
And make a check how this work in `Practice` mode.

**Comment by andy840119** [comment]
This issue can be closed due to fixed.
