### ISSUE TITLE
Double click to cut might cause index error in lyric editor.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#441]
Image:
![image](https://user-images.githubusercontent.com/9100368/106349608-937dfa00-6312-11eb-89e8-5b300ba912ab.png)
In lyric utils.

Call stack : 
```
   at osu.Game.Rulesets.Karaoke.Utils.LyricsUtils.SplitLyric(Lyric lyric, Int32 splitIndex) in F:\Github\osu-Karaoke\osu-Karaoke-release\osu.Game.Rulesets.Karaoke\Utils\LyricsUtils.cs:line 31
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.LyricManager.SplitLyric(Lyric lyric, Int32 index) in F:\Github\osu-Karaoke\osu-Karaoke-release\osu.Game.Rulesets.Karaoke\Edit\Lyrics\LyricManager.cs:line 109
   at osu.Game.Rulesets.Karaoke.Edit.Lyrics.Components.Lyrics.LyricControl.OnDoubleClick(DoubleClickEvent e) in F:\Github\osu-Karaoke\osu-Karaoke-release\osu.Game.Rulesets.Karaoke\Edit\Lyrics\Components\Lyrics\LyricControl.cs:line 130
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.MouseButtonEventManager.handleDoubleClick(InputState state, List`1 targets)
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonDown(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonDown(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.PassThroughInputManager.Handle(UIEvent e)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonDown(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonDown(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.InputManager.Update()
   at osu.Framework.Input.PassThroughInputManager.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
```

**Comment by andy840119** [comment]
Fixed in #498
