### ISSUE TITLE
Fix got error if first open setting overlay.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#819]
![image](https://user-images.githubusercontent.com/9100368/130345570-74008629-cb26-4659-a7fe-e6c55fad08e3.png)

This error only appears if have the karaoke ruleset.

Here's the log:
```
2021-08-22 06:50:42 [error]: An unobserved error has occurred.
2021-08-22 06:50:42 [error]: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
2021-08-22 06:50:42 [error]: ---> System.NullReferenceException: Object reference not set to an instance of an object.
2021-08-22 06:50:42 [error]: at lambda_method1457(Closure , DatabasedSetting )
2021-08-22 06:50:42 [error]: at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.ReadPropertyValue(IPropertyBase propertyBase)
2021-08-22 06:50:42 [error]: at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(InternalEntityEntry entry)
2021-08-22 06:50:42 [error]: at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
2021-08-22 06:50:42 [error]: at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges()
2021-08-22 06:50:42 [error]: at Microsoft.EntityFrameworkCore.DbContext.TryDetectChanges()
2021-08-22 06:50:42 [error]: at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
2021-08-22 06:50:42 [error]: at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
2021-08-22 06:50:42 [error]: at osu.Game.Database.DatabaseWriteUsage.Dispose(Boolean disposing)
2021-08-22 06:50:42 [error]: at osu.Game.Database.DatabaseWriteUsage.Dispose()
2021-08-22 06:50:42 [error]: at osu.Game.Configuration.SettingsStore.Update(DatabasedSetting setting)
2021-08-22 06:50:42 [error]: at osu.Game.Configuration.DatabasedConfigManager`1.PerformSave()
2021-08-22 06:50:42 [error]: at osu.Framework.Configuration.ConfigManager.Save()
2021-08-22 06:50:42 [error]: at osu.Framework.Configuration.ConfigManager.<>c__DisplayClass3_0.<QueueBackgroundSave>b__0(Task task)
2021-08-22 06:50:42 [error]: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2021-08-22 06:50:42 [error]: --- End of stack trace from previous location ---
2021-08-22 06:50:42 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2021-08-22 06:50:42 [error]: --- End of inner exception stack trace ---
2021-08-22 06:50:42 [error]: An unobserved error has occurred. (inner)
2021-08-22 06:50:42 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2021-08-22 06:50:42 [error]: at lambda_method1457(Closure , DatabasedSetting )
2021-08-22 06:50:42 [error]: at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.ReadPropertyValue(IPropertyBase propertyBase)
2021-08-22 06:50:42 [error]: at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(InternalEntityEntry entry)
2021-08-22 06:50:42 [error]: at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
2021-08-22 06:50:42 [error]: at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges()
2021-08-22 06:50:42 [error]: at Microsoft.EntityFrameworkCore.DbContext.TryDetectChanges()
2021-08-22 06:50:42 [error]: at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
2021-08-22 06:50:42 [error]: at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
2021-08-22 06:50:42 [error]: at osu.Game.Database.DatabaseWriteUsage.Dispose(Boolean disposing)
2021-08-22 06:50:42 [error]: at osu.Game.Database.DatabaseWriteUsage.Dispose()
2021-08-22 06:50:42 [error]: at osu.Game.Configuration.SettingsStore.Update(DatabasedSetting setting)
2021-08-22 06:50:42 [error]: at osu.Game.Configuration.DatabasedConfigManager`1.PerformSave()
2021-08-22 06:50:42 [error]: at osu.Framework.Configuration.ConfigManager.Save()
2021-08-22 06:50:42 [error]: at osu.Framework.Configuration.ConfigManager.<>c__DisplayClass3_0.<QueueBackgroundSave>b__0(Task task)
2021-08-22 06:50:42 [error]: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2021-08-22 06:50:42 [error]: --- End of stack trace from previous location ---
2021-08-22 06:50:42 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by andy840119** [comment]
Fixed.
